ADD:ER図
namikawa07/Study_quest pull request #2
Opened 2021-03-17 06:15 UTC by namikawa07

ER図を作成しました！
ご確認よろしくお願いいたします。

2021-03-17 06:39 UTC, yuji91 requested changes
気になった点をコメントしました！

2021-03-17 06:39 UTC, yuji91 commented on README.md
> +https://drive.google.com/file/d/1cBd3F05dgtk3CXOrZmcywasDac0TIn5c/view?usp=sharing
- `@schedule.schedule_start_date`と重複するので`start_date`で良さそうです。
（end_dateも同様で、Missionについても同じ点があります。）

- `@note.note`と重複しているので、`@note.content`または`@note.body`などに変えた方が良いですね。

- `Character.img`は`image`の略称でしょうか？
カラム名には基本的に省略しない名称をつけましょう。

- 細かい点にはなりますが、ER図の名称が単数形と複数形が混ざっており、モデル名とテーブル名のどちらなのか分かりづらいので統一した方が良いと思います！

2021-03-17 07:15 UTC, namikawa07 commented on README.md
> +https://drive.google.com/file/d/1cBd3F05dgtk3CXOrZmcywasDac0TIn5c/view?usp=sharing
ご確認ありがとうございます！
ER図を変更いたしましたので確認お願いします！

2021-03-17 07:43 UTC, yuji91 commented on README.md
> +https://drive.google.com/file/d/1cBd3F05dgtk3CXOrZmcywasDac0TIn5c/view?usp=sharing
`start_date`に対応するのは`finish_date`ではなく`end_date`の方が良いかもしれません。

ただ細かい部分なので今の方がしっくり来るなら変えなくてもOKです！

2021-03-18 02:35 UTC, namikawa07 reviewed
わかりました！確かにfinish_dateは少しおかしいですね。finish_dateをend_dateに変更しましたので確認お願いします！

2021-03-18 02:35 UTC, namikawa07 commented on README.md
> +https://drive.google.com/file/d/1cBd3F05dgtk3CXOrZmcywasDac0TIn5c/view?usp=sharing
わかりました！確かにfinish_dateは少しおかしいですね。finish_dateをend_dateに変更しましたので確認お願いします！

2021-03-18 03:22 UTC, DaichiSaito commented
気になった点です！

- missionはユーザーに対して一つですか？
- missionに対してtaskが複数紐づくのかなと思ったんですが、missionとtaskは別に主従関係はないですか？
- missionとscheduleってどう違うんでしたっけ？別にしてる理由はありますか？画面設計てきにmissionとscheduleって密接に紐づくものなのかなと感じました。
- characterってどこで設定するんでしょうか？

2021-03-18 04:15 UTC, namikawa07 commented
・missionはユーザーに対して一つですか？
ー最初はmissionを複数個作れるようにして各missionに複数のタスクが設定できるようにしていたのですが、そうすると画面の数も多くなってくると思い使いづらいかなと思いました。またこのサービスは自分が主人公となりゲーム感覚でタスクを倒していくところに良さがあると思っていまして、もし複数のmissionを設定できるようにしても結局はタスクプレイ画面が一緒なのでmissionを多くすると逆にどのmissionもmission名が違うだけで似たり寄ったりしてくるかなと思いました。なので1つにmissionを絞った方がタスクプレイ画面を楽しんでもらえるかなと思いmissionは1つにしました。またmissionを複数個存在させるということはまずmissionを作成し、そこからゲーム画面に移行するといった形でゲーム画面まで段階を踏まないといけないことになるので、個人的にはログインしたらすぐにゲーム画面に飛べるような仕様にしたいと思っておりmissionは設定してもしなくても良い状態で、ログインすればすぐにゲーム画面まで飛べるような仕様にしました。

・missionに対してtaskが複数紐づくのかなと思ったんですが、missionとtaskは別に主従関係はないですか？
ーmissionとtaskは主従関係でした！変更しておきます！


・missionとscheduleってどう違うんでしたっけ？別にしてる理由はありますか？画面設計てきにmissionとscheduleって密接に紐づくものなのかなと感じました。
ー確かにmissionとscheduleは主従関係でした！変更します！

・characterってどこで設定するんでしょうか？
ーすいません、characterは自動で生成されるのでテーブルはいらなかったです。消しておきます！

・質問
missionは上記の理由から1つにしましたが複数ある方が確実に利便性は高いと思っています。
どちらが良いのか悩んでいるのでアドバイスいただけると幸いです。

長々とすいません。もし説明で理解できないところがあれば教えてください。
ご確認よろしくお願いします！

2021-03-18 04:25 UTC, DaichiSaito commented
> 個人的にはログインしたらすぐにゲーム画面に飛べるような仕様にしたいと思っておりmissionは設定してもしなくても良い状態で、ログインすればすぐにゲーム画面まで飛べるような仕様にしました。

> missionとtaskは主従関係でした！変更しておきます！

この二つ矛盾しませんか？

taskは必須だと認識してるんですが、missionに対する子のモデルなのでmissionがないとtaskも存在し得ないと思います。にもかかわらずmissionがなくてもアプリを使えるというところに疑問を感じました。

2021-03-18 05:26 UTC, namikawa07 commented
確かにそうですね。となるとやはりuserにtaskとscheduleを紐づける方が良いのでしょうか？

2021-03-18 06:55 UTC, DaichiSaito commented
要件が把握しきれてないので教えて欲しいのですが、
・missionとは
・taskとは
・scheduleとは

それぞれの役割・用途を教えていただけると！


> ・質問
> missionは上記の理由から1つにしましたが複数ある方が確実に利便性は高いと思っています。
> どちらが良いのか悩んでいるのでアドバイスいただけると幸いです。

ここについては上記の疑問を解決してから考えさせてください。

@namikawa07

2021-03-18 07:17 UTC, namikawa07 commented
missionとは全体で定める目標みたいなものです。その大きな目標のために毎日タスクを作成し、タスクを実行していきます。scheduleとはmissionで決めた大きな目標を細分化してそれぞれ定める小さな目標です。
例えばmissionでは「4/30にあるTOEICで600点をとる」と決めると自然と「今日~3/25は参考書Aを終わらす」「3/25~4/7で単語1000個覚える」といった感じに目標を対して逆算してやるべきタスクを細分化し(scheduleの用途)、そこから「今日のタスクは参考書Aのp.10~p.50まで読む」みたいに1日のタスクが決められる(taskの用途)と思っています。なのでそういう使い方ができるようにmissionとscheduleとtaskを作りました。

2021-03-18 07:30 UTC, DaichiSaito commented
なるほどです！

> missionは上記の理由から1つにしましたが複数ある方が確実に利便性は高いと思っています。

→ 利便性だけの話じゃないような気がしますね。
例えばmissionを一つにしちゃった場合、4/30のTOEICが終わったらユーザーはどうしますか？新しいミッションを課したい場合は既存のミッションを書き換える形になりますかね？となると「TOEICで600点を取る」というミッションが過去にあった事実は消えますね。それでも良いのであればmissionは一つで良いと思いますし、その場合はむしろmissionとtaskは全く別にしないといけないですね。

@namikawa07

2021-03-18 07:44 UTC, namikawa07 commented
確かにmissionを全て完了した後に次のmissionをするためにはデータを削除する必要があるという仕様はユーザー側にはデメリットなところになりますね。
missionを複数個付けれるという設定にして再度画面遷移頭とER図を作り直してみます！

2021-03-18 10:36 UTC, namikawa07 commented
画面遷移図とER図を書き直しましたのでご確認いただけると幸いです。

・画面遷移図
新しくマイページ内にミッション一覧を表示できるようにしました。
ミッション編集は鉛筆マークからアクセスできます。★マークは１件だけお気に入り登録でき、登録したミッションはメニューのplay taskからアクセスできるようになります。★マークを使わずともMymission内の各ミッションをクリックすると各ミッションのタスクプレイ画面にアクセスできます。ミッション作成はわざわざマイページからいく必要はなくメニューから直接飛べるようにしました。
またmission・schedule・taskの関係性もわかりづらかったのでタスクプレイ画面のtask’s informationでわかりやすくしました。

変更したスライド
・マイページ画面
・メニュー画面
・ミッション作成画面
・タスク実行画面

https://xd.adobe.com/view/32512a57-4036-4356-94ef-aa34a9e1d552-6702/



・ER図
お気に入り機能のfavoriteテーブルの書き方がよくわからなかったので間違っていたら教えてくださると幸いです。
今回は1userに対しお気に入りにできるのは1missionとなっているのでfavoriteテーブルが必要なのかわかりませんでした。

https://drive.google.com/file/d/1cBd3F05dgtk3CXOrZmcywasDac0TIn5c/view?usp=sharing

2021-03-19 08:31 UTC, Mutsuki1102 commented
> ミッション編集は鉛筆マークからアクセスできます。★マークは１件だけお気に入り登録でき、登録したミッションはメニューのplay taskからアクセスできるようになります。★マークを使わずともMymission内の各ミッションをクリックすると各ミッションのタスクプレイ画面にアクセスできます。ミッション作成はわざわざマイページからいく必要はなくメニューから直接飛べるようにしました。

「★マーク」って必要ありますか？本来「★マーク」はお気に入りを複数登録できる仕様になることが多いので、あまりおすすめできません。ユーザーにとっても分かりづらい動線になるので削除したほうが良いかと思うのですがいかがでしょうか。

2021-03-19 08:43 UTC, namikawa07 commented
今の状態ですとタスクプレイするためには「マイページにいく」→「マイミッションの実行したいタスクをクリック」という順番になるのですがそれをミッションを1つ登録するとメニューのタスクプレイから直接アクセスできるようにしたいと思っています！
確かにおっしゃる通り機能としてはユーザーが認識しているいくつも登録できるお気に入り機能ではないのでユーザー側からすると間違いますね。また別のビジュアルでmissionを登録できるようにしてみます！
また登録できるmissionが1つだけの場合はfavoriteテーブルではなくmissionテーブルのfavoriteタスクにしたほうがいいのでしょうか？？

2021-03-19 09:35 UTC, DaichiSaito commented
> また登録できるmissionが1つだけの場合はfavoriteテーブルではなくmissionテーブルのfavoriteタスクにしたほうがいいのでしょうか？？

missionが一つだけの場合はそもそも★って不要じゃないですか？

2021-03-20 07:59 UTC, namikawa07 commented
もともとあったMymissionをMIssionsに変更。★をMymissionに変更し、favoriteテーブルではなくmissionテーブルのfavoriteカラムに変更しました！
確認お願いします！

2021-03-20 08:46 UTC, DaichiSaito commented
missionとscheduledってなんで分けてるんでしたっけ？missionの中に全部入れるのだと何か不都合がありましたっけ？
@namikawa07

2021-03-20 08:52 UTC, namikawa07 commented
missionでは複数個のscheduleを設定したいと考えているので1対多の関係になるようにmissionsテーブルとschedulesテーブルを分けています！

2021-03-20 09:07 UTC, DaichiSaito commented
であればtaskにスケジュールを持たせるのではまずいですか？

2021-03-20 09:09 UTC, namikawa07 commented
taskテーブルにscheduleテーブルを紐づけるということでしょうか？

2021-03-20 09:17 UTC, DaichiSaito commented
あ、タスクの期限はまた別なんですね。

> 1つのmission内で複数個のscheduleを設定したい

これの具体的なイメージがつかなかったんですが、どういうケースでしょうか？
この画面を見る限りmissionに複数個のスケジュールが紐づくとは考えづらくて...！

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/2d30ec2c11e39e5195040b8f2d13e028.png)](https://startup-technology.gyazo.com/2d30ec2c11e39e5195040b8f2d13e028)

@namikawa07

2021-03-20 09:22 UTC, namikawa07 commented
missionの期間の中にいくつものscheduleの期間が入っている感じです！
[![Image from Gyazo](https://i.gyazo.com/e884b2be9ab245cadd7b2369dc7c4cf0.png)](https://gyazo.com/e884b2be9ab245cadd7b2369dc7c4cf0)

2021-03-21 06:22 UTC, merged